//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {


    public partial class contextControl
    {
       
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;

       
        protected global::System.Web.UI.WebControls.SqlDataSource selectMaxContextId;

       
        protected global::System.Web.UI.WebControls.SqlDataSource InsertTCI;

       
       protected global::System.Web.UI.WebControls.SqlDataSource ALLTechnology;

       
        protected global::System.Web.UI.WebControls.SqlDataSource RelatedImpact;

       
        protected global::System.Web.UI.WebControls.SqlDataSource ALLImpact;

        protected global::System.Web.UI.WebControls.FormView FormView1;

        protected global::System.Web.UI.WebControls.SqlDataSource RelatedTechnology;
        
    }
}
