//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {


    public partial class impactControl
    {
        protected global::System.Web.UI.WebControls.FormView FormView1;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected global::System.Web.UI.WebControls.SqlDataSource InsertDataISO_IMPACT;
        protected global::System.Web.UI.WebControls.SqlDataSource InsertTCI;
        protected global::System.Web.UI.WebControls.SqlDataSource selectMaxImpactId;
        protected global::System.Web.UI.WebControls.Panel mainP;

        
    }
}
