//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class InsertNew
    {
        protected global::System.Web.UI.WebControls.Label ListofTech;
        protected global::System.Web.UI.WebControls.Label ListofContext;
        protected global::System.Web.UI.WebControls.Label ListofImpact;
        protected global::System.Web.UI.WebControls.Label selectedTech;
        protected global::System.Web.UI.WebControls.Label selectedContext;
        protected global::System.Web.UI.WebControls.Label selectedImpact;
        
        protected global::System.Web.UI.WebControls.DropDownList technologyList;
        protected global::System.Web.UI.WebControls.DropDownList contextList;
        protected global::System.Web.UI.WebControls.DropDownList impactList;
        protected global::System.Web.UI.WebControls.Panel technologyControlPanel;
        protected global::System.Web.UI.WebControls.Panel contextControlPanel;
        protected global::System.Web.UI.WebControls.Panel impactControlPanel;
        protected global::System.Web.UI.WebControls.Button InsertImp;
        protected global::System.Web.UI.WebControls.Button InsertCont;
        protected global::System.Web.UI.WebControls.Button ButtonNext;
        protected global::System.Web.UI.WebControls.SqlDataSource ALL_Context;

    }
}
